/* cbor.h — hand-written CBOR subset: definite-length maps/arrays with
 * integer keys, uint/nint, tstr/bstr, bool/null, float64, over a caller
 * buffer. No dynamic allocation, no ESP-IDF dependency (this file and
 * cbor.c build standalone under the host compiler — see firmware/host/).
 *
 * Authority: docs/DEVICE_PLAN.md §2.4 ("Firmware codec"), docs/PROTOCOL.md
 * §10 (the normative integer keymap this module is agnostic to — callers
 * pass whichever key an envelope field maps to; this module does not know
 * the keymap itself).
 *
 * Wire subset (RFC 8949 definite-length forms only):
 *   major 0 unsigned int, major 1 negative int, major 2 byte string,
 *   major 3 text string, major 4 array, major 5 map, major 7 simple
 *   (false/true/null) and float64. Every length/count/key uses the
 *   shortest encoding that fits (RFC 8949 §4.2.1-style preferred
 *   serialization), which is what makes the round-trip in
 *   firmware/host/test_cbor.c byte-identical to tools/authvectors.json's
 *   cbor_signed_b64 vectors (generated by the relay's cbor2).
 *
 * Indefinite-length items (additional info 31) and the reserved
 * additional-info values 28-30 are rejected outright — every reader
 * function returns false rather than attempt to interpret them. Tags
 * (major 6) are not part of this protocol's wire format and are likewise
 * rejected.
 *
 * This module has no modem or sleep-state effect of its own: it only
 * reads/writes memory the caller owns.
 *
 * Key parameter convention: every keyed writer/reader takes the
 * already-resolved PROTOCOL.md §10 integer key as a plain `uint32_t` — this
 * module does not hold or validate the keymap.
 *
 * Nested maps (`cbor_w_map_key`): the writer list a caller reads out of
 * DEVICE_TASKS.md's F3.2 "Do" step names `cbor_w_map(w, n)` (no key, for
 * the outermost envelope map) and separately says an encoder must support
 * "nested map" values (PROTOCOL.md §10's `cfg` field, key 38, whose value
 * is itself a map, and whose `lock` sub-field, key 0, is *itself* a map —
 * two levels of map-as-value). Writing a map as a *value* under a key needs
 * a key to be emitted first, which `cbor_w_map(w, n)` (by its given,
 * key-less signature) cannot do. `cbor_w_map_key(w, key, n)` fills that gap
 * the same way `cbor_w_array(w, key, n)` already does for arrays-as-values;
 * `cbor_w_map(w, n)` remains for the root map and for the unkeyed map
 * headers that open each element of an array-of-maps (this protocol's `c[]`
 * and `p[]`).
 */
#ifndef CBOR_H
#define CBOR_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ---------------------------------------------------------------------
 * Writer
 * --------------------------------------------------------------------- */

typedef struct {
    uint8_t *buf;
    size_t cap;
    size_t len;
    bool err; /* sticky: once true, every write function is a no-op that
               * returns false, so a caller can skip per-call checks and
               * check `w->err` (or the return of a final call) once. */
} cbor_w_t;

/* Binds `w` to `buf[0..cap)`. Does not touch `buf`. */
void cbor_w_init(cbor_w_t *w, uint8_t *buf, size_t cap);

/* Writes a definite-length map header for `n` pairs. Used for the
 * outermost envelope map and for each unkeyed map that opens an
 * array-of-maps element (see cbor_w_array). Returns false (and sets
 * w->err) on overflow. */
bool cbor_w_map(cbor_w_t *w, uint32_t n);

/* Writes `key` then a definite-length map header for `n` pairs — a map
 * *value* nested under a key (see the "Nested maps" note above). */
bool cbor_w_map_key(cbor_w_t *w, uint32_t key, uint32_t n);

/* Writes `key` then a definite-length array header for `n` items. Each of
 * the `n` items is then written by the caller in sequence, unkeyed —
 * in this protocol every array item is itself a map, opened with a bare
 * cbor_w_map(w, m). */
bool cbor_w_array(cbor_w_t *w, uint32_t key, uint32_t n);

/* Scalar key/value pairs. Each writes `key` (major 0, shortest form) then
 * the value. */
bool cbor_w_uint(cbor_w_t *w, uint32_t key, uint64_t u);
/* `v` MUST be negative (major 1 has no representation for >= 0); returns
 * false without writing anything if it is not. */
bool cbor_w_nint(cbor_w_t *w, uint32_t key, int64_t v);
bool cbor_w_tstr(cbor_w_t *w, uint32_t key, const char *s, size_t len);
bool cbor_w_bstr(cbor_w_t *w, uint32_t key, const uint8_t *b, size_t len);
bool cbor_w_bool(cbor_w_t *w, uint32_t key, bool v);
bool cbor_w_null(cbor_w_t *w, uint32_t key);
/* Always major 7 / additional info 27 (float64, 9 bytes on the wire) —
 * this module never emits float16/float32, matching DEVICE_PLAN.md §2.4
 * ("lat/lon as float64"). */
bool cbor_w_f64(cbor_w_t *w, uint32_t key, double v);

/* ---------------------------------------------------------------------
 * Reader
 * --------------------------------------------------------------------- */

typedef struct {
    const uint8_t *buf;
    size_t len;
    size_t pos;
} cbor_r_t;

typedef enum {
    CBOR_T_UINT,
    CBOR_T_NINT,
    CBOR_T_BSTR,
    CBOR_T_TSTR,
    CBOR_T_ARRAY,
    CBOR_T_MAP,
    CBOR_T_BOOL,
    CBOR_T_NULL,
    CBOR_T_FLOAT64,
    CBOR_T_INVALID, /* indefinite length, a reserved additional-info value,
                      * a tag, or end of buffer */
} cbor_type_t;

void cbor_r_init(cbor_r_t *r, const uint8_t *buf, size_t len);

/* Looks at the next item without consuming it. Callers use this to decide
 * which typed getter to call for a value whose type is not known ahead of
 * time (e.g. copying an unknown-shape map). */
cbor_type_t cbor_r_peek(const cbor_r_t *r);

/* Consumes a definite-length map/array header, returning the element
 * (map: pair) count. False, position unchanged, if the next item is not a
 * map/array or has an indefinite length. */
bool cbor_r_map(cbor_r_t *r, uint32_t *count);
bool cbor_r_array(cbor_r_t *r, uint32_t *count);

/* Reads a map key (always major 0 / unsigned in this protocol). */
bool cbor_r_key(cbor_r_t *r, uint32_t *key);

bool cbor_r_uint(cbor_r_t *r, uint64_t *v);
bool cbor_r_nint(cbor_r_t *r, int64_t *v); /* value returned negative */
/* `*s` points into the reader's own buffer — not NUL-terminated, no copy. */
bool cbor_r_tstr(cbor_r_t *r, const char **s, size_t *len);
bool cbor_r_bstr(cbor_r_t *r, const uint8_t **b, size_t *len);
bool cbor_r_bool(cbor_r_t *r, bool *v);
bool cbor_r_null(cbor_r_t *r);
bool cbor_r_f64(cbor_r_t *r, double *v); /* float64 only; float16/32 rejected */

/* Skips the next value, whatever its type, recursively for maps/arrays.
 * For ignoring an unknown key's value while walking a map. */
bool cbor_r_skip(cbor_r_t *r);

#ifdef __cplusplus
}
#endif

#endif /* CBOR_H */
